const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
const hash=async text=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(x=>x.toString(16).padStart(2,'0')).join('');
const token=()=>crypto.randomUUID()+crypto.randomUUID();
async function ensureUsers(env){const count=await env.DB.prepare('SELECT COUNT(*) total FROM users').first();if(Number(count?.total||0)>0||!env.USER_SEEDS)return;const seeds=JSON.parse(env.USER_SEEDS);await env.DB.batch(seeds.map(u=>env.DB.prepare('INSERT OR IGNORE INTO users(username,name,role,password_hash) VALUES(?,?,?,?)').bind(u.username,u.name,u.role,u.password_hash)))}
async function currentUser(req,env){const bearer=req.headers.get('authorization')?.replace(/^Bearer\s+/,'');if(!bearer)return null;return env.DB.prepare("SELECT u.username,u.name,u.role FROM sessions s JOIN users u ON u.username=s.username WHERE s.token=? AND s.expires_at>datetime('now') AND u.active=1").bind(bearer).first()}
async function body(req){try{return await req.json()}catch{return {}}}
async function api(req,env){const url=new URL(req.url),path=url.pathname;
 if(path==='/api/auth/login'&&req.method==='POST'){await ensureUsers(env);const b=await body(req),username=String(b.username||'').toLowerCase().trim();const passwordHash=await hash(`aksi-tempel-v1:${b.password||''}`);const user=await env.DB.prepare('SELECT username,name,role FROM users WHERE username=? AND password_hash=? AND active=1').bind(username,passwordHash).first();if(!user)return json({error:'Username atau password tidak sesuai.'},401);const t=token(),expires=new Date(Date.now()+8*60*60*1000).toISOString();await env.DB.prepare('INSERT INTO sessions(token,username,expires_at) VALUES(?,?,?)').bind(t,username,expires).run();return json({token:t,user})}
 const user=await currentUser(req,env);if(!user)return json({error:'Sesi tidak valid.'},401);
 if(path==='/api/auth/me')return json({user});
 if(path==='/api/arrears'&&req.method==='GET'){const result=user.role==='admin'?await env.DB.prepare('SELECT * FROM arrears ORDER BY imported_at DESC LIMIT 5000').all():await env.DB.prepare('SELECT * FROM arrears WHERE assigned_to=? ORDER BY assigned_at DESC LIMIT 2000').bind(user.username).all();return json({rows:result.results})}
 if(path==='/api/arrears/import'&&req.method==='POST'){if(user.role!=='admin')return json({error:'Khusus admin.'},403);const b=await body(req),rows=Array.isArray(b.rows)?b.rows.slice(0,5000):[];const statements=rows.map(r=>env.DB.prepare('INSERT OR REPLACE INTO arrears(id,no_polisi,nama_pemilik,nomor_hp,alamat,jatuh_tempo,jenis_kendaraan,samsat_asal,prioritas,imported_by) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),String(r.no_polisi||'').toUpperCase(),r.nama_pemilik_terakhir||r.nama_pemilik||'',String(r.nomor_hp||''),r.alamat_pemilik_terakhir||r.alamat||'',String(r.tgl_mati_yad||r.jatuh_tempo||''),r.deskripsi_jenis_kendaraan||r.jenis_kendaraan||'',r.samsat_asal_nama||r.samsat_asal||'',r.prioritas||'',user.username));if(statements.length)await env.DB.batch(statements);return json({imported:statements.length})}
 if(path==='/api/arrears/assign'&&req.method==='POST'){if(user.role!=='admin')return json({error:'Khusus admin.'},403);const b=await body(req),ids=Array.isArray(b.ids)?b.ids.slice(0,1000):[],assignee=String(b.assignee||'');const valid=await env.DB.prepare("SELECT username FROM users WHERE username=? AND role='user' AND active=1").bind(assignee).first();if(!valid)return json({error:'Petugas tidak valid.'},400);if(ids.length)await env.DB.batch(ids.map(id=>env.DB.prepare("UPDATE arrears SET assigned_to=?,assigned_by=?,assigned_at=datetime('now'),status='Ditugaskan' WHERE id=?").bind(assignee,user.username,id)));return json({assigned:ids.length})}
 return json({error:'Tidak ditemukan.'},404)}
export default {async fetch(req,env){const url=new URL(req.url);if(url.pathname.startsWith('/api/'))return api(req,env);const asset=await env.ASSETS.fetch(req);if(asset.status!==404||req.method!=='GET')return asset;return env.ASSETS.fetch(new Request(new URL('/index.html',req.url),req))}};
