import React,{useEffect,useMemo,useRef,useState} from 'react';
import QRCode from 'qrcode';
import Tesseract from 'tesseract.js';
import * as XLSX from 'xlsx';
import {buildNoticeId,connectZebraBridge,disconnectZebraBridge,downloadPrinterPayload,getZebraBridgeStatus,getZebraCapability,sendToZebraBridge,testZebraBridge,TAX_INFO_URL} from './printerService';
import {ACCOUNTS,apiFetch,getCaptcha,authenticate,isSuperAdmin,isAdmin,isUser} from './auth';

const makeIcon=s=>(p)=><span className={p?.className||'icon'} aria-hidden="true">{s}</span>;
const Camera=makeIcon('\u{1F4F7}'),Upload=makeIcon('\u{2B06}'),Search=makeIcon('\u{2300}'),MapPin=makeIcon('\u{1F4CD}'),User=makeIcon('\u{1F464}'),MessageCircle=makeIcon('\u{1F4AC}'),CalendarDays=makeIcon('\u{1F4C5}'),CheckCircle2=makeIcon('\u{2713}'),AlertTriangle=makeIcon('\u{26A0}'),Database=makeIcon('\u{25A6}'),FileDown=makeIcon('\u{21E9}'),Trash2=makeIcon('\u{1F5D1}'),RefreshCw=makeIcon('\u{21BB}'),X=makeIcon('\u{00D7}'),ClipboardList=makeIcon('\u{258F}'),BarChart3=makeIcon('\u{25A5}'),Printer=makeIcon('\u{1F5A8}'),History=makeIcon('\u{25F7}'),Shield=makeIcon('\u{1F6E1}'),UserPlus=makeIcon('\u{2695}'),Settings=makeIcon('\u{2699}'),Lock=makeIcon('\u{1F512}');

const today=()=>new Date().toISOString().slice(0,10);
const normalizePlate=s=>s.toUpperCase().replace(/[^A-Z0-9]/g,'').replace(/^BM(\d{1,4})([A-Z]{1,3})$/,'BM-$1-$2');
const displayPlate=s=>{const n=s.toUpperCase().replace(/[^A-Z0-9]/g,'');const m=n.match(/BM(\d{1,4})([A-Z]{1,3})/);return m?'BM-'+m[1]+'-'+m[2]:s.toUpperCase()};
const OCR_CHAR_FIX={O:'0',Q:'0',D:'0',I:'1',L:'1',Z:'2',S:'5',G:'6',B:'8'};
const normalizeOcrLine=l=>l.toUpperCase().replace(/[|]/g,'I').replace(/[^A-Z0-9]/g,'');
const findPlates=text=>{const lines=text.toUpperCase().split(/\n|\r/).map(normalizeOcrLine).filter(Boolean);const joined=normalizeOcrLine(text);const sources=[...lines,joined];const out=[];for(const raw of sources){const start=raw.indexOf('BM');const variants=start>=0?[raw.slice(start),raw]:[raw];for(const value of variants){const m=value.match(/^B[MNHW]?([A-Z0-9]{1,4})([A-Z]{1,3})/);if(!m)continue;const digits=m[1].split('').map(c=>/\d/.test(c)?c:(OCR_CHAR_FIX[c]??c)).join('');const suffix=m[2].replace(/[012568]/g,c=>({'0':'O','1':'I','2':'Z','5':'S','6':'G','8':'B'}[c]));if(/^\d{1,4}$/.test(digits)&&/^[A-Z]{1,3}$/.test(suffix))out.push('BM-'+digits+'-'+suffix)}}return[...new Set(out)]};
const findPlate=text=>findPlates(text)[0]||'';
const plateKey=s=>String(s).replace(/[^A-Z0-9]/g,'').toUpperCase();
const editDistance=(a,b)=>{const dp=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=0;i<=a.length;i++)dp[i][0]=i;for(let j=0;j<=b.length;j++)dp[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return dp[a.length][b.length]};
const closestPlate=(candidate,db)=>{const key=plateKey(candidate);let best=null;for(const row of db){const p=plateKey(row.no_polisi);if(!p||Math.abs(p.length-key.length)>2)continue;const d=editDistance(key,p);if(!best||d<best.distance)best={plate:displayPlate(row.no_polisi),distance:d,row};if(d===0)break;}return best&&best.distance<=2?best:null};
const loadImage=src=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=src});
const makeProcessedCanvas=(img,crop,threshold=false)=>{const sx=Math.round(img.width*crop.x),sy=Math.round(img.height*crop.y),sw=Math.max(1,Math.round(img.width*crop.w)),sh=Math.max(1,Math.round(img.height*crop.h));const scale=Math.min(3,Math.max(1.5,1600/sw));const canvas=document.createElement('canvas');canvas.width=Math.round(sw*scale);canvas.height=Math.round(sh*scale);const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,sx,sy,sw,sh,0,0,canvas.width,canvas.height);const data=ctx.getImageData(0,0,canvas.width,canvas.height);for(let i=0;i<data.data.length;i+=4){const g=.299*data.data[i]+.587*data.data[i+1]+.114*data.data[i+2];let v=Math.max(0,Math.min(255,(g-128)*1.65+128));if(threshold)v=v>145?255:0;data.data[i]=data.data[i+1]=data.data[i+2]=v}ctx.putImageData(data,0,0);return canvas};
const phone62=v=>{let s=String(v||'').replace(/\D/g,'');if(!s||s==='0')return'';if(s.startsWith('0'))s='62'+s.slice(1);else if(!s.startsWith('62'))s='62'+s;return s};
const waText=r=>'Yth. Bapak/Ibu pemilik kendaraan '+r.no_polisi+'. Berdasarkan kegiatan Aksi Tempel-Tempel Jasa Raharja, kendaraan teridentifikasi memiliki kewajiban yang perlu ditindaklanjuti. Mohon melakukan pengecekan dan pembayaran melalui layanan Samsat resmi. Terima kasih.';
const imageToEvidence=async file=>{const source=URL.createObjectURL(file);try{const img=await loadImage(source);const max=1280;const ratio=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*ratio);canvas.height=Math.round(img.height*ratio);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.76)}finally{URL.revokeObjectURL(source)}};

function LoginScreen({onLogin}){
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[captchaAnswer,setCaptchaAnswer]=useState('');
 const [captcha,setCaptcha]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{getCaptcha().then(c=>{if(c)setCaptcha(c)})},[]);
 async function submit(e){
  e.preventDefault();setLoading(true);setError('');
  const account=await authenticate(username,password,captcha?.token,captchaAnswer);
  setLoading(false);
  if(!account){setError('Username, password, atau jawaban captcha tidak sesuai.');const c=await getCaptcha();if(c)setCaptcha(c);setCaptchaAnswer('');return}
  setError('');onLogin(account)
 }
 function refreshCaptcha(){setCaptcha(null);setCaptchaAnswer('');getCaptcha().then(c=>{if(c)setCaptcha(c)})}
 return <main className="login-page"><section className="login-panel">
  <div className="login-brand"><div className="logo">AT</div><div><b>AKSI TEMPEL DIGITAL</b><span>Tim Pembina Samsat Provinsi Riau</span></div></div>
  <h1>Masuk Petugas</h1>
  <p>Gunakan akun yang telah diberikan untuk mengakses kegiatan lapangan.</p>
  <form onSubmit={submit}>
   <label>Username<input autoCapitalize="none" autoCorrect="off" autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} placeholder="nama.pengguna" disabled={loading}/></label>
   <label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder={'••••••••••'} disabled={loading}/></label>
   {captcha&&<label className="captcha-label"><span className="captcha-q">Captcha: {captcha.question}</span><div className="input-icon"><Lock/><input type="number" value={captchaAnswer} onChange={e=>setCaptchaAnswer(e.target.value)} placeholder="Jawaban" disabled={loading} required/></div><button type="button" className="link-btn" onClick={refreshCaptcha} disabled={loading}>Ganti Soal</button></label>}
   {error&&<div className="login-error">{error}</div>}
   <button className="primary" type="submit" disabled={loading||!captcha}>{loading?'Memverifikasi...':'Masuk'}</button>
  </form>
  <small>Akses dibatasi sesuai level akun. Super Admin, Admin, dan Petugas.</small>
 </section></main>
}

function Stat({label,value,icon}){return<div className="stat"><div>{icon}</div><span>{label}</span><b>{value}</b></div>}
function DataTable({rows,blast,remove,setStatus,openNotice,canBlast,canDelete}){return<div className="table-wrap"><table><thead><tr><th>Waktu</th><th>Nopol & Kendaraan</th><th>Pemilik</th><th>Petugas / Lokasi</th><th>Bukti</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.time}</b><small>{r.date}</small></td><td><strong className="plate">{r.no_polisi}</strong><small>{r.deskripsi_jenis_kendaraan||'Tidak diketahui'}</small></td><td><b>{r.nama_pemilik_terakhir}</b><small>{r.nomor_hp&&r.nomor_hp!=='0'?r.nomor_hp:'WA tidak tersedia'}</small></td><td><b>{r.petugas}</b><small>{r.lokasi}</small></td><td>{r.foto?<img className="evidence-thumb" src={r.foto}/>:<small>Tanpa foto</small>}<small>{r.print_status||'Belum Dicetak'}</small></td><td><select className="status" value={r.status} onChange={e=>setStatus(r.id,e.target.value)}><option>Belum Dihubungi</option><option>WA Dibuka</option><option>Sudah Dihubungi</option><option>Selesai</option></select></td><td><div className="actions"><button title="Cetak notice" onClick={()=>openNotice(r)}><Printer/></button>{canBlast&&<button title="WhatsApp" onClick={()=>blast(r)}><MessageCircle/></button>}{canDelete&&<button className="danger" title="Hapus" onClick={()=>remove(r.id)}><Trash2/></button>}</div></td></tr>)}{!rows.length&&<tr><td colSpan="7"><div className="empty">Belum ada temuan pada tanggal ini.</div></td></tr>}</tbody></table></div>}

function CaptureView({onCapture,db,loadingDb}){
 const [photo,setPhoto]=useState(''),[ocr,setOcr]=useState(false),[progress,setProgress]=useState(0);
 const [plate,setPlate]=useState(''),[location,setLocation]=useState(''),[date,setDate]=useState(today());
 const inputRef=useRef();
 const match=useMemo(()=>{const p=displayPlate(plate).replace(/[^A-Z0-9]/g,'');return db.find(x=>String(x.no_polisi||'').replace(/[^A-Z0-9]/g,'').toUpperCase()===p)},[db,plate]);
 function getLocation(){if(!navigator.geolocation){setLocation('Lokasi tidak didukung browser');return}navigator.geolocation.getCurrentPosition(p=>setLocation(p.coords.latitude.toFixed(6)+', '+p.coords.longitude.toFixed(6)),()=>setLocation('Lokasi gagal diambil — isi manual'))}
 async function onFile(file){if(!file)return;const url=URL.createObjectURL(file);setPlate('');setOcr(true);setProgress(1);try{const img=await loadImage(url);setPhoto(await imageToEvidence(file));const crops=[{x:.1,y:.2,w:.8,h:.6},{x:.2,y:.55,w:.6,h:.35},{x:.05,y:.3,w:.9,h:.4},{x:.15,y:.45,w:.7,h:.4}];let selected='',nearest=null;for(let i=0;i<crops.length&&!selected;i++){const canvas=makeProcessedCanvas(img,crops[i],true);const result=await Tesseract.recognize(canvas,'eng',{logger:m=>{if(m.status==='recognizing text')setProgress(Math.min(99,Math.round(((i+(m.progress||0)*.5)/crops.length)*100)))},tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',tessedit_pageseg_mode:'7',preserve_interword_spaces:'1'});const candidates=findPlates(result.data.text);for(const c of candidates){const exact=db.find(r=>plateKey(r.no_polisi)===plateKey(c));if(exact){selected=displayPlate(exact.no_polisi);break}const close=closestPlate(c,db);if(close&&(!nearest||close.distance<nearest.distance))nearest=close}if(selected)break}setProgress(100);if(selected)setPlate(selected);else if(nearest){setPlate(nearest.plate);alert('OCR mendekati '+nearest.plate+' dan telah dicocokkan dengan database. Silakan periksa kembali sebelum menyimpan.')}else{alert('Nomor polisi belum terbaca. Silakan ketik nomor polisi secara manual di bawah, atau ambil foto lebih dekat ke plat nomor.')}}catch(e){console.error(e);alert('OCR gagal: '+(e?.message||String(e)))}finally{URL.revokeObjectURL(url);setOcr(false);setTimeout(()=>setProgress(0),500)}}
 function save(){if(!plate.trim())return alert('Nomor polisi wajib diisi.');if(!location.trim())return alert('Lokasi wajib diisi.');onCapture({date,location,plate:displayPlate(plate),photo,match});setPlate('');setPhoto('')}
 return<section className="capture-grid"><div className="card photo-card"><div className="card-title"><Camera/>Foto Plat Nomor</div><div className={'dropzone '+(photo?'has-photo':'')} onClick={()=>inputRef.current.click()}>{photo?<><img src={photo}/><button className="clear" onClick={e=>{e.stopPropagation();setPhoto('')}}><X/></button></>:<><div className="camera-circle"><Camera/></div><b>Ambil foto atau unggah gambar</b><span>Pastikan plat terlihat jelas dan memenuhi bingkai</span></>}{ocr&&<div className="ocr"><RefreshCw className="spin"/>Membaca plat... {progress}%</div>}</div><input ref={inputRef} hidden type="file" accept="image/*" capture="environment" onChange={e=>onFile(e.target.files[0])}/><button className="outline" onClick={()=>inputRef.current.click()}><Upload/>Pilih Foto</button></div><div className="card form-card"><div className="card-title"><ClipboardList/>Data Kegiatan</div><label>Nomor Polisi<div className="input-icon"><Search/><input value={plate} onChange={e=>setPlate(e.target.value.toUpperCase())} placeholder="BM 1234 AB"/></div></label>{plate&&<div className={'match '+(match?'found':'notfound')}>{match?<><CheckCircle2/><div><b>Data ditemukan</b><span>{match.nama_pemilik_terakhir} • {match.deskripsi_jenis_kendaraan||''}</span></div></>:<><AlertTriangle/><div><b>Belum ditemukan di database</b><span>Tetap dapat disimpan sebagai temuan baru</span></div></>}</div>}<div className="two"><label>Tanggal<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><label>Lokasi Pengambilan<div className="location-row"><div className="input-icon"><MapPin/><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Contoh: Pasar Cik Puan / koordinat"/></div><button className="loc" onClick={getLocation}><MapPin/></button></div></label><button className="primary" onClick={save}><CheckCircle2/>Simpan ke Rekap Hari Ini</button></div></section>
}

function DailyView({date,setDate,entries,session,setStatus,remove,blast,openNotice,exportExcel}){
 const filtered=useMemo(()=>{return entries.filter(e=>e.date===date)},[entries,date]);
 const [query,setQuery]=useState('');
 const displayed=useMemo(()=>query?filtered.filter(e=>JSON.stringify(e).toLowerCase().includes(query.toLowerCase())):filtered,[filtered,query]);
 const matched=filtered.filter(e=>e.nama_pemilik_terakhir!=='Tidak ditemukan').length;
 const validPhones=filtered.filter(e=>phone62(e.nomor_hp)).length;
 const printedCount=filtered.filter(e=>e.print_status&&e.print_status!=='Belum Dicetak').length;
 return<><section className="stats"><Stat label="Temuan Hari Ini" value={filtered.length} icon={<Camera/>}/><Stat label="Cocok Database" value={matched} icon={<Database/>}/><Stat label="Nomor WA Valid" value={validPhones} icon={<MessageCircle/>}/><Stat label="Notice Tercetak" value={printedCount} icon={<Printer/>}/></section><section className="card table-card"><div className="toolbar"><div className="input-icon search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari nopol, pemilik, lokasi, petugas..."/></div><button className="outline compact" onClick={exportExcel}><FileDown/>Export Excel</button></div><DataTable rows={displayed} blast={blast} remove={remove} setStatus={setStatus} openNotice={openNotice} canBlast={isAdmin(session)} canDelete={isSuperAdmin(session)}/></section></>
}

function DashboardView({entries,session}){
 const stats=useMemo(()=>{const petugas=[...new Set(entries.map(e=>e.petugas).filter(Boolean))];const lokasi=Object.entries(entries.reduce((a,e)=>(a[e.lokasi]=(a[e.lokasi]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]).slice(0,8);return{petugas,lokasi,total:entries.length,days:new Set(entries.map(e=>e.date)).size,waValid:entries.filter(e=>phone62(e.nomor_hp)).length,selesai:entries.filter(e=>e.status==='Selesai').length}},[entries]);
 return<><section className="stats"><Stat label="Total Temuan" value={stats.total} icon={<Camera/>}/><Stat label="Hari Aktif" value={stats.days} icon={<CalendarDays/>}/><Stat label="WA Tersedia" value={stats.waValid} icon={<MessageCircle/>}/><Stat label="Selesai" value={stats.selesai} icon={<CheckCircle2/>}/></section><section className="dashboard-grid">{isAdmin(session)&&<div className="card"><div className="card-title"><User/>Kinerja Seluruh Petugas</div>{stats.petugas.map(u=>{const n=entries.filter(e=>e.petugas===u).length;return<div className="barrow" key={u}><span>{u}</span><div><i style={{width:Math.min(100,n/Math.max(1,entries.length)*100)+'%'}}/></div><b>{n}</b></div>})}</div>}<div className="card"><div className="card-title"><MapPin/>Lokasi Teratas{isUser(session)?' Saya':''}</div>{stats.lokasi.map(([k,v])=><div className="rank" key={k}><span>{k}</span><b>{v}</b></div>)}{!entries.length&&<div className="empty">Belum ada data kegiatan.</div>}</div></section></>
}

function VehicleHistoryView({entries,openNotice}){
 const [finder,setFinder]=useState('');
 const results=useMemo(()=>{const key=plateKey(finder);return key?entries.filter(e=>plateKey(e.no_polisi).includes(key)).sort((a,b)=>`${b.date} ${b.time}`.localeCompare(`${a.date} ${a.time}`)):[]},[entries,finder]);
 const latest=useMemo(()=>Object.values(entries.reduce((acc,e)=>{const k=plateKey(e.no_polisi);if(!acc[k]||`${e.date} ${e.time}`>`${acc[k].date} ${acc[k].time}`)acc[k]=e;return acc},{})).sort((a,b)=>`${b.date} ${b.time}`.localeCompare(`${a.date} ${a.time}`)),[entries]);
 const list=finder?results:latest;
 return<><section className="card finder-card"><div className="card-title"><Search/>Cari Riwayat Kendaraan</div><div className="input-icon search"><Search/><input value={finder} onChange={e=>setFinder(e.target.value.toUpperCase())} placeholder="Masukkan nomor polisi, contoh BM 9929 FN"/></div><p className="privacy-note">Gunakan data posisi dan foto hanya untuk kebutuhan pelayanan atau penelusuran yang sah dan berwenang.</p></section><section className="sighting-grid">{list.map((r,index)=><article className="card sighting" key={r.id}>{r.foto?<img src={r.foto} alt={'Bukti '+r.no_polisi}/>:<div className="no-photo"><Camera/>Tidak ada foto</div>}<div className="sighting-body"><div className="sighting-top"><strong className="plate">{r.no_polisi}</strong>{index===0&&finder?<span className="latest-badge">Terakhir terlihat</span>:null}</div><h3>{r.date} • {r.time}</h3><p><MapPin/> {r.lokasi}</p><p><User/> {r.petugas}</p><small>ID Notice: {r.notice_id||'-'}</small><button className="outline" onClick={()=>openNotice(r)}><Printer/>Buka Notice</button></div></article>)}{!list.length&&<div className="card empty">Belum ada riwayat kendaraan yang cocok.</div>}</section></>
}

function NoticeView({notice,entries,select,language,setLanguage,browserPrint,zebraPrint,download}){
 const capability=useMemo(getZebraCapability,[]);
 const [printer,setPrinter]=useState({connected:false,status:capability.bridgeAvailable?'Siap dihubungkan':'Bridge belum tersedia'});
 const [showHelp,setShowHelp]=useState(false);
 async function connect(){try{const r=await connectZebraBridge();setPrinter({connected:Boolean(r?.ok||r?.connected),status:r?.name||r?.deviceName||(r?.ok?'Zebra tersambung':'Koneksi gagal')})}catch(e){setPrinter({connected:false,status:e?.message||'Koneksi gagal'})}}
 async function refresh(){const r=await getZebraBridgeStatus();setPrinter({connected:Boolean(r?.connected),status:r?.name||r?.deviceName||(r?.connected?'Zebra tersambung':'Tidak tersambung')})}
 async function disconnect(){await disconnectZebraBridge();setPrinter({connected:false,status:'Koneksi diputus'})}
 async function test(){try{await testZebraBridge(language);alert('Test print berhasil dikirim.')}catch(e){alert('Test print gagal: '+(e?.message||e))}}
 return<section className="notice-layout"><div className="card notice-controls"><div className="card-title"><Printer/>Cetak Notice</div><div className={'printer-status '+(printer.connected?'connected':'disconnected')}><i/><div><b>{printer.connected?'Printer tersambung':'Printer belum tersambung'}</b><span>{printer.status}</span></div></div><div className="printer-connect-actions"><button className="outline" onClick={connect} disabled={!capability.bridgeAvailable}>Hubungkan</button><button className="outline" onClick={refresh} disabled={!capability.bridgeAvailable}>Periksa</button><button className="outline" onClick={disconnect} disabled={!printer.connected}>Putuskan</button></div><label>Pilih temuan<select value={notice?.id||''} onChange={e=>select(entries.find(x=>x.id===e.target.value)||null)}><option value="">Pilih kendaraan</option>{entries.map(e=><option key={e.id} value={e.id}>{e.no_polisi} — {e.date} {e.time}</option>)}</select></label><label>Bahasa printer<select value={language} onChange={e=>setLanguage(e.target.value)}><option>CPCL</option><option>ZPL</option></select></label><div className="notice-print-btns"><button className="primary" disabled={!notice||!printer.connected} onClick={zebraPrint}><Printer/>Cetak ke Zebra</button><button className="outline" disabled={!notice} onClick={browserPrint}>Cetak Sistem / PDF</button><button className="outline" disabled={!notice} onClick={download}><FileDown/>Unduh {language}</button></div><button className="link-btn" onClick={()=>setShowHelp(!showHelp)}>{showHelp?'Sembunyikan panduan':'Panduan koneksi printer'}</button>{showHelp&&<div className="printer-note"><b>{capability.platform==='ios'?'iPhone: Gunakan Zebra MFi SDK':'Android: Gunakan Zebra Printer SDK'}</b><span>Bluetooth Classic/SPP tidak dijamin dari browser. Hubungkan printer via aplikasi Zebra companion, lalu kembali ke sini untuk cetak.</span><span>Pastikan printer menyala dan sudah dipasangkan di Bluetooth settings perangkat.</span></div>}</div>{notice?<div className="notice-preview-wrap"><ThermalNotice notice={notice}/></div>:<div className="card empty">Pilih temuan untuk melihat preview notice sebelum cetak.</div>}</section>
}

function ArrearsView({session}){
 const [rows,setRows]=useState([]),[selected,setSelected]=useState([]),[assignee,setAssignee]=useState('siti.izriskiah'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const input=useRef();
 async function load(){try{const r=await apiFetch('/api/arrears');const d=await r.json();if(!r.ok)throw new Error(d.error);setRows(d.rows||[])}catch(e){setMessage(e.message||'Database produksi belum tersedia.')}}
 useEffect(()=>{load()},[]);
 async function upload(file){if(!file)return;setBusy(true);try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),data=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});const r=await apiFetch('/api/arrears?action=import',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({rows:data})}),d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(d.imported+' data tunggakan berhasil dimasukkan.');await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function assign(){if(!selected.length)return;setBusy(true);try{const r=await apiFetch('/api/arrears?action=assign',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ids:selected,assignee})}),d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(d.assigned+' data dibagikan ke '+assignee+'.');setSelected([]);await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return<section className="card table-card">{isAdmin(session)&&<div className="arrears-admin"><input ref={input} hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>upload(e.target.files[0])}/><button className="outline compact" onClick={()=>input.current.click()} disabled={busy}><Upload/>Tambah Data Tunggakan</button><select value={assignee} onChange={e=>setAssignee(e.target.value)}>{ACCOUNTS.filter(a=>a.role==='user').map(a=><option key={a.username} value={a.username}>{a.name}</option>)}</select><button className="primary compact" onClick={assign} disabled={busy||!selected.length}>Bagikan {selected.length||''} Data</button></div>}{message&&<div className="sync-message">{message}</div>}<div className="table-wrap"><table><thead><tr>{isAdmin(session)&&<th>Pilih</th>}<th>Nopol</th><th>Pemilik</th><th>Jatuh Tempo</th><th>Prioritas</th><th>Ditugaskan Kepada</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{isAdmin(session)&&<td><input type="checkbox" checked={selected.includes(r.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,r.id]:v.filter(x=>x!==r.id))}/></td>}<td><strong className="plate">{r.no_polisi}</strong></td><td><b>{r.nama_pemilik||'-'}</b><small>{r.nomor_hp||'WA tidak tersedia'}</small></td><td>{r.jatuh_tempo||'-'}</td><td>{r.prioritas||'-'}</td><td>{r.assigned_to||'Belum dibagikan'}</td><td>{r.status}</td></tr>)}{!rows.length&&<tr><td colSpan="7"><div className="empty">Belum ada data tunggakan.</div></td></tr>}</tbody></table></div></section>
}

function UserManagementView(){
 const [users,setUsers]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[form,setForm]=useState({username:'',name:'',position:'',role:'user',password:''});
 async function load(){try{const r=await apiFetch('/api/users');const d=await r.json();if(!r.ok)throw new Error(d.error);setUsers(d.rows||[])}catch(e){setMessage(e.message)}}
 useEffect(()=>{load()},[]);
 async function addUser(e){e.preventDefault();setBusy(true);try{const r=await apiFetch('/api/users',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)throw new Error(d.error);setForm({username:'',name:'',position:'',role:'user',password:''});setMessage(form.username+' berhasil ditambahkan.');await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function deleteUser(username){if(!confirm('Hapus akun '+username+'?'))return;setBusy(true);try{const r=await apiFetch('/api/users',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({username})}),d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(username+' dihapus.');await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 function genPassword(){const name=form.name.split(' ')[0].toLowerCase();const num=Math.floor(Math.random()*900)+100;return name+num}
 return<section className="card table-card"><div className="card-title"><UserPlus/>Kelola Akun Petugas</div>{message&&<div className="sync-message">{message}</div>}<form className="user-form" onSubmit={addUser}><div className="two"><label>Nama Lengkap<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required disabled={busy}/></label><label>Username<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} required disabled={busy}/></label></div><div className="two"><label>Jabatan/Posisi<input value={form.position} onChange={e=>setForm({...form,position:e.target.value})} disabled={busy}/></label><label>Level<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} disabled={busy}><option value="user">Petugas (User)</option><option value="admin">Admin</option></select></label></div><div className="two"><label>Password<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required disabled={busy}/></label><label><span style={{display:'block',marginBottom:10}}>&nbsp;</span><button type="button" className="outline compact" style={{height:45}} onClick={()=>setForm({...form,password:genPassword()})}>Generate Password</button></label></div><button className="primary compact" type="submit" disabled={busy}>Tambah User</button></form><div className="table-wrap"><table><thead><tr><th>Username</th><th>Nama</th><th>Jabatan</th><th>Level</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{users.map(u=><tr key={u.username}><td><strong>{u.username}</strong></td><td><b>{u.name}</b><small>{u.position||'-'}</small></td><td>{u.position||'-'}</td><td><span className={'role-badge role-'+u.role}>{u.role==='super_admin'?'Super Admin':u.role==='admin'?'Admin':'Petugas'}</span></td><td>{u.active?'Aktif':'Nonaktif'}</td><td><div className="actions"><button className="danger" title="Hapus" onClick={()=>deleteUser(u.username)}><Trash2/></button></div></td></tr>)}{!users.length&&<tr><td colSpan="6"><div className="empty">Belum ada akun.</div></td></tr>}</tbody></table></div></section>
}

function ThermalQr(){const [src,setSrc]=useState('');useEffect(()=>{QRCode.toDataURL(TAX_INFO_URL,{width:240,margin:1,errorCorrectionLevel:'M'}).then(setSrc).catch(console.error)},[]);return<a className="qr-placeholder" href={TAX_INFO_URL} target="_blank" rel="noreferrer" aria-label="Buka Info Pajak Bapenda Riau">{src?<img src={src} alt="QR Info Pajak Bapenda Riau"/>:<span>QR</span>}<small>Scan untuk cek info pajak terkini</small></a>}
function ThermalNotice({notice}){return<article className="thermal-notice" id="thermal-notice"><div className="notice-heading"><b>TIM PEMBINA SAMSAT</b><strong>PROVINSI RIAU</strong></div><div className="notice-rule"/><h2>PEMBERITAHUAN KEPATUHAN<br/>PAJAK KENDARAAN BERMOTOR</h2><div className="notice-plate">{notice.no_polisi}</div><dl><div><dt>Terpantau</dt><dd>{notice.date} • {notice.time} WIB</dd></div><div><dt>Lokasi</dt><dd>{notice.lokasi}</dd></div></dl><p>Berdasarkan hasil monitoring lapangan, kendaraan ini <b>terindikasi belum memenuhi kewajiban pembayaran PKB dan/atau SWDKLLJ</b> sesuai data yang tersedia pada saat pemeriksaan.</p><p>Apabila kewajiban telah dipenuhi, abaikan pemberitahuan ini. Terima kasih atas kepatuhan Anda.</p><div className="notice-benefit"><b>PEMBAYARAN RESMI</b><span>Kantor Samsat • Samsat Keliling<br/>Gerai Samsat • SIGNAL</span></div><ThermalQr/><div className="souvenir-message"><b>BAWA KERTAS INI KE SAMSAT</b><span>untuk melakukan pembayaran dan dapatkan souvenir dari Tim Pembina Samsat.</span></div><div className="notice-id">ID NOTICE<br/><b>{notice.notice_id}</b></div><footer><b>BAPENDA • POLRI • PT JASA RAHARJA</b><span>TIM PEMBINA SAMSAT PROVINSI RIAU</span></footer></article>}

function ProfileSettingsView({session,onLogout}){
 const [profile,setProfile]=useState(null);
 const [oldPwd,setOldPwd]=useState(''),[newPwd,setNewPwd]=useState(''),[confirmPwd,setConfirmPwd]=useState('');
 const [email,setEmail]=useState(''),[verifToken,setVerifToken]=useState('');
 const [msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const [tab,setTab]=useState('profile');
 useEffect(()=>{apiFetch('/api/users?action=profile').then(async r=>{const d=await r.json();if(r.ok&&d.profile){setProfile(d.profile);setEmail(d.profile.email||'')}}).catch(()=>{})},[]);
 async function changePassword(e){e.preventDefault();if(newPwd!==confirmPwd)return setMsg('Password baru tidak cocok.');setBusy(true);setMsg('');try{const r=await apiFetch('/api/auth/manage?action=change-password',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({old_password:oldPwd,new_password:newPwd})}),d=await r.json();if(!r.ok)throw new Error(d.error);setMsg('Password berhasil diubah.');setOldPwd('');setNewPwd('');setConfirmPwd('')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function linkEmail(e){e.preventDefault();setBusy(true);setMsg('');try{const r=await apiFetch('/api/auth/manage?action=link-email',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email})}),d=await r.json();if(!r.ok)throw new Error(d.error);setVerifToken(d.verification_token);setMsg('Token verifikasi: '+d.verification_token+'. Gunakan untuk verifikasi.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function verifyEmail(){if(!verifToken)return setMsg('Masukkan token verifikasi.');setBusy(true);setMsg('');try{const r=await apiFetch('/api/auth/manage?action=verify-email',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({verification_token:verifToken})}),d=await r.json();if(!r.ok)throw new Error(d.error);setProfile({...profile,email:d.email,email_verified:true});setVerifToken('');setMsg('Email berhasil diverifikasi.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return<section className="card table-card"><div className="card-title"><Settings/>Profil & Pengaturan</div>{msg&&<div className={'sync-message '+(msg.includes('berhasil')?'msg-ok':'')}>{msg}</div>}
  <div className="profile-tabs"><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}>Profil Saya</button><button className={tab==='password'?'active':''} onClick={()=>setTab('password')}>Ubah Password</button><button className={tab==='email'?'active':''} onClick={()=>setTab('email')}>Email & Pemulihan</button></div>
  {tab==='profile'&&<div className="profile-info">{profile&&<>
   <div className="profile-field"><span>Nama</span><b>{profile.name}</b></div>
   <div className="profile-field"><span>Username</span><b>{profile.username}</b></div>
   <div className="profile-field"><span>Jabatan</span><b>{profile.position||'-'}</b></div>
   <div className="profile-field"><span>Level</span><span className={'role-badge role-'+profile.role}>{profile.role==='super_admin'?'Super Admin':profile.role==='admin'?'Admin':'Petugas'}</span></div>
   <div className="profile-field"><span>Email</span><b>{profile.email||'Belum ditautkan'}{profile.email_verified?' ✓ Terverifikasi':''}</b></div>
   <div className="profile-field"><span>Terdaftar sejak</span><b>{new Date(profile.created_at).toLocaleDateString('id-ID')}</b></div>
  </>}</div>}
  {tab==='password'&&<form className="profile-form" onSubmit={changePassword}>
   <label>Password Lama<input type="password" value={oldPwd} onChange={e=>setOldPwd(e.target.value)} required disabled={busy}/></label>
   <label>Password Baru<input type="password" value={newPwd} onChange={e=>setNewPwd(e.target.value)} required minLength={6} disabled={busy}/></label>
   <label>Konfirmasi Password Baru<input type="password" value={confirmPwd} onChange={e=>setConfirmPwd(e.target.value)} required disabled={busy}/></label>
   <button className="primary compact" type="submit" disabled={busy}>Simpan Password</button>
  </form>}
  {tab==='email'&&<div className="profile-email">
   {!profile?.email_verified?<>
    <p className="privacy-note">Tautkan email untuk pemulihan akun jika lupa password.</p>
    <form className="profile-form" onSubmit={linkEmail}>
     <label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@contoh.com" required disabled={busy}/></label>
     <button className="primary compact" type="submit" disabled={busy}>Kirim Token Verifikasi</button>
    </form>
    {verifToken&&<div className="verify-section"><label>Token Verifikasi<input value={verifToken} onChange={e=>setVerifToken(e.target.value)} placeholder="Paste token di sini"/></label><button className="outline compact" onClick={verifyEmail} disabled={busy}>Verifikasi Email</button></div>}
   </>:<div className="email-verified"><b>Email terverifikasi</b><span>{profile.email}</span><small>Email sudah aktif untuk pemulihan akun.</small></div>}
  </div>}
 </section>
}

export{LoginScreen,CaptureView,DailyView,DashboardView,VehicleHistoryView,NoticeView,ArrearsView,ThermalNotice,ThermalQr,UserManagementView,ProfileSettingsView};
